### GET - Display all categories
GET http://localhost:8080/categories


### POST - Add a new category
POST http://localhost:8080/categories/add?name=Category no4&description=This is a category no4
Content-Type: application/x-www-form-urlencoded


### PUT - Edit an existing category
PUT http://localhost:8080/categories/edit/1
Content-Type: application/x-www-form-urlencoded



### GET - Delete a category
GET http://localhost:8080/categories/delete/1

